#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <bucket-name>"
    exit 1
fi

BUCKET_NAME=$1

echo -e "\n***** Deleting S3 Bucket: $BUCKET_NAME *****\n"

aws s3api delete-bucket --bucket "$BUCKET_NAME"

if [ $? -ne 0 ]; then
    echo -e "\nError: Failed to delete bucket $BUCKET_NAME"
    exit 1
else
    echo -e "\nBucket $BUCKET_NAME deleted successfully."
fi